[package]
name = "belief_spread"
version = "0.1.0"
authors = ["Robert Greener"]
edition = "2021"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
